#!/bin/bash
#
#                         License
#
# Copyright (C) 2022  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# This script automates the execution of linpack.  It will determine the
# set of default run parameters based on the system configuration.
#

error_exit()
{
	echo $1
	exit $2
}

usage()
{
	echo "$1 Usage:"
	echo "  --interleave: numactl interleave option"
	source test_tools/general_setup --usage
	exit 1
}

test_name="linpack"
if [ ! -f "/tmp/${test_name}.out" ]; then
        command="${0} $@"
        echo $command
        $command &> /tmp/${test_name}.out
	rtc=$?
        cat /tmp/${test_name}.out
        rm -f /tmp/${test_name}.out
        exit $rtc
fi

arguments="$@"

curdir=`pwd`

if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
elif [[ $0 != "/"* ]]; then
	dir=`echo $0 | rev | cut -d'/' -f2- | rev`
	run_dir="${curdir}/${dir}"
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
	if [[ $run_dir != "/"* ]]; then
		run_dir=${curdir}/${run_dir}
	fi
fi

setup_done=0
out_file=""
interleave="all"
show_usage=0

#
# Clone the repo that contains the common code and tools
#
tools_git=https://github.com/redhat-performance/test_tools-wrappers

found=0
for arg in "$@"; do
	if [ $found -eq 1 ]; then
		tools_git=$arg
		found=0
	fi
	if [[ $arg == "--tools_git" ]]; then
		found=1
	fi

	#
	# We do the usage check here, as we do not want to be calling
	# the common parsers then checking for usage here.  Doing so will
	# result in the script exiting with out giving the test options.
	#
	if [[ $arg == "--usage" ]]; then
		show_usage=1
	fi
done

#
# Check to see if the test tools directory exists.  If it does, we do not need to
# clone the repo.
#
if [ ! -d "test_tools" ]; then
        git clone $tools_git test_tools
        if [ $? -ne 0 ]; then
                error_exit "pulling git $tools_git failed." 1
        fi
fi

if [ $show_usage -eq 1 ]; then
	usage $test_name
fi


#
# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_run_label: Label for the run
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#

${curdir}/test_tools/gather_data ${curdir}
source test_tools/general_setup "$@"
export TOOLS_BIN

execute_via_shell()
{
	if [ $setup_done -eq 0 ]; then
		cp $run_dir/linpack_extra/* $run_dir/linpack
		file=`/$to_home_root/$to_user/tools_bin/get_params_file -d /$to_home_root/$to_user -t ${test_name} -c ${to_sysname}`
		if test -f "$file"; then
			cp $file $run_dir/${test_name}/linpack.dat
		fi
		rm -rf $run_dir/results_${test_name}_${to_tuned_setting}_numa_interleave_${interleave}
		if [[ ! -d $run_dir/${test_name}/results_${test_name}_${to_tuned_setting}_numa_interleave_${interleave} ]]; then
			mkdir -p $run_dir/${test_name}/results_${test_name}_${to_tuned_setting}_numa_interleave_${interleave}
		fi
		rm -f /tmp/results_${test_name}_${to_tuned_setting}_numa_interleave_${interleave}
		setup_done=1
	fi
	file=`/$to_home_root/$to_user/tools_bin/get_params_file -d /$to_home_root/$to_user -t ${test_name} -c ${to_sysname}`
	if test -f "$file"; then
		while IFS= read -r linpack_ops
		do
			options=`echo "${linpack_ops}" | cut -d':' -f 2`
			test_config=`echo "${linpack_ops}" | cut -d':' -f 1`
			config="${to_configuration}_${test_config}"
			cd $run_dir/${test_name}
			echo ./run_linpack.sh -u \"$to_user\" -h $to_home_root -C $to_configuration -i $to_times_to_run -P $to_tuned_setting -s $to_sysname -n $interleave
			./run_linpack.sh -u \"$to_user\" -h $to_home_root -C $to_configuration -i $to_times_to_run -P $to_tuned_setting -s $to_sysname -n $interleave >> $out_file
			if [ $? -ne 0 ]; then
				error_exit "run_linpack.sh failed" 1
			fi
		done  < "$file"
	else
		cd $run_dir/${test_name}
		echo ./run_linpack.sh -u \"$to_user\" -h $to_home_root -C $to_configuration -i $to_times_to_run -P $to_tuned_setting -s $to_sysname  -n $interleave
		./run_linpack.sh -u \"$to_user\" -h $to_home_root -C $to_configuration -i $to_times_to_run -P $to_tuned_setting -s $to_sysname -n $interleave >> $out_file
		if [ $? -ne 0 ]; then
			error_exit "run_linpack.sh failed" 1
		fi
	fi
}

# Define options
#
ARGUMENT_LIST=(
	"interleave"
)

NO_ARGUMENTS=(
)

# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
    --name "$(basename "$0")" \
    --options "h" \
    -- "$@"
)

#
# Report any errors
#
if [ $? -ne 0 ]; then
	usage $test_name
fi

eval set --$opts

while [[ $# -gt 0 ]]; do
        case "$1" in
		--interleave)
			interleave=${2}
			shift 2
		;;
		-h)
			usage $test_name
		;;
		--)
			break; 
		;;
		*)
			error_exit "option not found $1" 1
		;;
        esac
done

if [[ ! -d "$run_dir/linpack" ]]; then
	mkdir $run_dir/linpack
fi
cp ${curdir}/uploads/xlinpack_xeon64-NEW ${run_dir}/linpack/xlinpack_xeon64
if [ $? -ne 0 ]; then
	error_exit "Error, did not find xlinpack_xeon64-NEW" 1
fi
chmod 755 ${run_dir}/linpack/xlinpack_xeon64

# Gather hardware information
${curdir}/test_tools/gather_data ${curdir}

rm -rf $run_dir/linpack/linpack_results  $run_dir/linpack/results*

# Get PCP setup if we're using it
pdir=""
if [[ $to_use_pcp -eq 1 ]]; then
	source $TOOLS_BIN/pcp/pcp_commands.inc
	setup_pcp
	pcp_cfg=$TOOLS_BIN/pcp/default.cfg
	pcpdir=/tmp/pcp_`date "+%Y.%m.%d-%H.%M.%S"`
	pdir="--copy_dir $pcpdir"
	start_pcp ${pcpdir}/ ${test_name} $pcp_cfg
fi

for iteration in  `seq 1 1 $to_times_to_run`
do
#If we're using PCP, snap a chalk line at the start of the iteration
	if [[ $to_use_pcp -eq 1 ]]; then
		start_pcp_subset
	fi
	out_file=/tmp/${test_name}_${to_tuned_setting}_numa_interleave_${interleave}_iteration_$iteration.out
	execute_via_shell
	# If we're using PCP, snap the chalk line at the end of the iteration
	# and log the iteration's result

	if [[ $to_use_pcp -eq 1 ]]; then
		linpack_data=`mktemp /tmp/passmark_data.XXXXX`
		results2pcp_add_value "iteration:${iteration}"
		grep ^ht linpack_results/results.csv  | grep -v cpu_affin > $linpack_data
		while IFS= read -r line
		do
			value=`echo $line | cut -d: -f1`
			#
			# Note: If we ever get to having more then 2 hyperthreads in the future, this
			# will need to be updated.  For now value of 1 indicates 2 hyperthreads.
			#
			if [[ $value == *"yes"* ]]; then
				results2pcp_add_value "hyper_thread:1"
			else
				results2pcp_add_value "hyper_thread:0"
			fi
			value=`echo $line | cut -d, -f2`
			results2pcp_add_value "num_sockets:$value"
			value=`echo $line | cut -d, -f3`
			results2pcp_add_value "numthreads:$value"
			value=`echo $line | cut -d, -f5`
			results2pcp_add_value "gflops:$value"
			#
			# Commit the metrics
			#
			results2pcp_add_value_commit
		done < "${linpack_data}"
		rm $linpack_data
		#
		# Reset metrics
		#
		reset_pcp_om
		stop_pcp_subset
	fi
done

if [[ $to_use_pcp -eq 1 ]]; then
	stop_pcp
	shutdown_pcp
fi

#
# Process the data.
#
${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --results linpack_results/results.csv --test_name $test_name --tuned_setting=$to_tuned_setting --version NONE --user $to_user --other_files "linpack_results/test_results_report,${curdir}/hw_info.out" $pdir
exit 0
